import next from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

import base from '@banking/config/eslint/base';

/**
 * `eslint-config-next` ships a native flat config from v16, so it composes
 * directly. Earlier versions were eslintrc-only and needed `FlatCompat` as a
 * bridge — that bridge now fails outright on the new shape, which is a clearer
 * signal than it silently half-working.
 */
const config = [
  // Generated by Next.js and rewritten on every build — linting it only ever
  // produces findings that cannot be fixed.
  { ignores: ['next-env.d.ts', '.next/**'] },
  ...base,
  ...next,
  ...nextTypescript,
];

export default config;
