import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

import base from '@banking/config/eslint/base';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  // Generated by Next.js and rewritten on every build — linting it only ever
  // produces findings that cannot be fixed.
  { ignores: ['next-env.d.ts', '.next/**'] },
  ...base,
  // `next/core-web-vitals` is still published as an eslintrc config; FlatCompat
  // is the supported bridge until Next.js ships a flat config.
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
